- docs/src/hugo/content/index.md
Renders the index page correctly for me on hugo-0.22.1.
> Use index layout for index page

- http/build.sbt
It's defaults to `publishSigned`, which is still publishing to Maven.  We want to just execute the `publish` step (same as sbt-release's default) in the http module in order to publish to the Docker registry.
> releasePublishArtifactsAction should publish Docker image

- project/plugins.sbt
This contains a downgrade of sbt-release, which was a working version on older
versions of rig. Let's see if this automates the release of jars to Maven
Central.
> Test new rig for publishing jars to Maven Central

- bin/generate-keys
- bin/generate-token
- Clean up the output of the install script to prevent prompts from printing on the same line
- Change the interpreter in the generate-keys script to prevent an error when trying to run with ./
> Clean up install script output, fix interpreter

- core/src/main/scala/cleanup/CleanupCron.scala
- core/src/main/scala/cleanup/ExpirationPolicy.scala
- core/src/main/scala/cleanup/GarbageCollector.scala
- core/src/main/scala/cleanup/Reaper.scala
- core/src/main/scala/cleanup/package.scala
- core/src/test/scala/CleanupSpec.scala
- core/src/test/scala/GarbageCollectorSpec.scala
- core/src/test/scala/ReaperSpec.scala
Deployments can get orphaned in a couple of corner cases. This PR addresses this by only applying the expiration policy to routable deployments. By doing this we only allow routable deployments the change to extend their lease. All other deployments (including orphans) will naturally expire and get cleaned up.
> cleanup process only applies expiration policy to routable deployments

- http/build.sbt
dl-3 no longer has the Docker artifact we need.  dl-2 does, but it's an old version and leaves us open to the mutability of what lies behind dl-cdn.  Instead, this uses the version of Docker (17.05.0-r0) that is in our version of alpine.
The risk is that we have trouble digesting the output, but if so, we can deal with that in a subsequent revision.  The build is broke anyway, yo.
> Use the Docker that Alpine gives us

- core/src/main/resources/nelson/defaults.cfg
- core/src/main/scala/Config.scala
- core/src/main/scala/Datacenter.scala
- core/src/main/scala/KubernetesClient.scala
- core/src/main/scala/Nelson.scala
- core/src/main/scala/Workflow.scala
- core/src/main/scala/health/KubernetesHealthClient.scala
- core/src/main/scala/scheduler/DeploymentSummary.scala
- core/src/main/scala/scheduler/KubernetesHttp.scala
- core/src/main/scala/scheduler/NomadHttp.scala
- core/src/main/scala/scheduler/SchedulerOp.scala
- core/src/main/scala/workflows/Canopus.scala
- core/src/test/resources/nelson/datacenters-missing-consul.cfg
- core/src/test/resources/nelson/datacenters-missing-domain.cfg
- core/src/test/resources/nelson/datacenters.cfg
- core/src/test/scala/NelsonSuite.scala
- docs/src/hugo/content/index.md
- etc/development/docker/nelson.cfg
- etc/development/http/http.dev.cfg
* Add Kubernetes interpreter for SchedulerOp
* Add new Canopus workflow for Kubernetes deployments
* Add new 'scheduler' field in config to choose between Nomad or Kubernetes
* Add support for SSLContext in HTTP4S Client creation
* Add namespace to Summary ctor since Kubernetes needs that
Also:
* Change Alpine APK endpoint as original one didn't seem to work anymore
* Remove Allocations, was only used in reconcilliation which was removed in #48
> Kubernetes integration for Nelson

- core/src/main/scala/CatsHelpers.scala
- core/src/main/scala/Metrics.scala
- core/src/main/scala/Templates.scala
- core/src/test/scala/AlertSpec.scala
- core/src/test/scala/PoliciesSpec.scala
- http/src/main/scala/Main.scala
- http/src/main/scala/MonitoringServer.scala
- project/versions.scala
- Change unsafeTimed to be safe using new IO cancellation feature
- Make Metrics.timer logic clearer
- Replace remaining uses of Task with IO
> Remove remaining Tasks and cleanup some migrations

- core/src/main/scala/Config.scala
- core/src/main/scala/Datacenter.scala
- core/src/main/scala/Exceptions.scala
- core/src/main/scala/KubernetesClient.scala
- core/src/main/scala/Manifest.scala
- core/src/main/scala/StubbedConsulClient.scala
- core/src/main/scala/yaml/ManifestV1Parser.scala
- core/src/test/resources/nelson/manifest.v1.everything.yml
- core/src/test/scala/ConfigSpec.scala
- core/src/test/scala/Fixtures.scala
- core/src/test/scala/yaml/ManifestYamlSpec.scala
- http/build.sbt
Initially started as just implementing volume mounts, but added some other stuff too..
- Add support for empty "scratch" directory volume mounts
- Add support for K8s 1.9.x and 1.10.x
- Allow operators to choose between in or out of cluster - if deploying in-cluster it will assuming the appropriate RBAC is configured and use Pod-mounted certs
- Build image to run as non-root
- Stub Consul client in K8s mode so we don't get bogus Consul errors in logs
> More Kubernetes features and additions

- core/src/main/resources/nelson/canopus_cron_job.mustache
- core/src/main/resources/nelson/canopus_job.mustache
- core/src/main/resources/nelson/canopus_service.mustache
Tested against live Kubernetes cluster (in-cluster deployment)
- Surround string values in quotes - without this, "strings" that
are valid instances of other types (e.g. true) are rejected by
Kubernetes
- Fix "schema" of container and environment variable object specs
- Work around some more instances of the Scalate indentation issue
Closes #108
> Fix default blueprints

- core/src/main/resources/nelson/defaults.cfg
- http/build.sbt
- project/plugins.sbt
Previously the `nelson` user was set to UID `1000`, which tends to be the default admin user on a given OS. This is strictly not safe as we want to be very explicit about how we map permissions. When using the nelson container, it is typical that people should create a service account on the OS that maps to a privileged user; something like:
```
sudo useradd -r -s /bin/false -u 2000 nelson
sudo usermod -L nelson
```
> Change the default nelson UID inside the container

- docs/build.sbt
- docs/src/hugo/content/downloads.md
- docs/src/hugo/layouts/shortcodes/cli_version.html
so that the docs site knows what the latest version is without having to hardcode it
> dynamically include the nelson-cli release data 

- core/src/main/scala/InstrumentedVaultClient.scala
- core/src/main/scala/Workflow.scala
- core/src/main/scala/vault/http/Http4sVault.scala
- core/src/main/scala/vault/op.scala
- core/src/main/scala/workflows/Pulsar.scala
- core/src/test/scala/NelsonSuite.scala
* Add support for deleting kubernetes roles
* Fix an issue with the Pulsar workflow not correctly cleaning up Vault stack policies.
resolves #139
> Add support for deleting kubernetes roles

- core/src/main/resources/nelson/defaults.cfg
- core/src/main/scala/Config.scala
- core/src/main/scala/Metrics.scala
- core/src/main/scala/Templates.scala
- core/src/test/resources/nelson/nelson-test.cfg
- core/src/test/scala/TemplatesSpec.scala
resolves https://github.com/getnelson/nelson/issues/148
The container side of this was implemented here: https://github.com/getnelson/containers/pull/3 allowing arbitrary rendering engines to be used, as desired.
> Migrate to v2.0 of the end user template linting containers

- core/src/main/scala/Config.scala
- core/src/main/scala/Datacenter.scala
- docs/src/hugo/content/getting-started/install.md
Fixes #180 
Currently, the AWS infrastructure configuration demands the use of basic credentials. While these can be securely provided through a number of solutions, falling back on IAM discovery can eliminate their need entirely when users are operating on a platform which supports use of the EC2 metadata service.
> support EC2/ECS discovery for credentials

- docs/src/hugo/content/documentation/manifest.md
Fixes
`[opt-outs](#manifest-unit-alerting-opt-out)`
`[Prometheus documentation](https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/)`
from https://getnelson.io/documentation/manifest.html#manifest-unit-alerting-syntax
> remove literal markdown syntax when hugo renders page

- core/src/main/scala/Nelson.scala
- etc/development/http/http.dev.cfg
- http/src/main/scala/plans/Blueprints.scala
Got into a sticky situation where a user uploaded a template that was not parsable, breaking all the templating listing and inspection capabilities. This PR adds more validation to the server side to prevent these kinds of accidents
> Raise hell if the names are empty or the template is bad

- core/src/main/resources/nelson/defaults.cfg
- core/src/main/scala/Config.scala
- core/src/main/scala/Datacenter.scala
- core/src/main/scala/loadbalancers/Aws.scala
- core/src/test/resources/nelson/datacenters-valid-aws.cfg
- core/src/test/resources/nelson/datacenters.cfg
- core/src/test/scala/ConfigSpec.scala
- docs/src/hugo/content/documentation/configuration.md
This adds the ability to specify that the ELB that nelson launches is `internal`. For more information see: https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-internal-load-balancers.html
> Have the ability to specify an ELB as internal

- core/build.sbt
- core/src/main/resources/nelson/defaults.cfg
- core/src/main/scala/Config.scala
- core/src/main/scala/Datacenter.scala
- core/src/main/scala/loadbalancers/Aws.scala
- core/src/test/resources/nelson/datacenters-aws-missing-elb-scheme.cfg
- core/src/test/resources/nelson/datacenters-missing-private-subnet.cfg
- core/src/test/resources/nelson/datacenters-missing-subnet.cfg
- core/src/test/resources/nelson/datacenters-valid-aws.cfg
- core/src/test/resources/nelson/datacenters.cfg
- docs/src/hugo/content/documentation/configuration.md
- version.sbt
This change is needed to bring Nelson into the recent world. This change prevents having to redeploy Nelson when updating ingress clusters, and instead relies on the fact that launch templates are in fact pointers to a particular revision of launch config (under the hood). In this way, Nelson gets a "static" launch template definition, whilst out-of-band people can manage their launch templates with Terraform / Cloud formation (or bash scripts, you animals), and then manage the upgrades to the ingress cluster machines.
> Upgrade from launch configurations to launch templates

- core/src/main/scala/InstrumentedVaultClient.scala
- core/src/main/scala/Workflow.scala
- core/src/main/scala/vault/http/Http4sVault.scala
- core/src/main/scala/vault/http/json.scala
- core/src/main/scala/vault/op.scala
- core/src/main/scala/workflows/Pulsar.scala
- core/src/test/scala/NelsonSuite.scala
Branching off of #233:
"In Vault, the PKI engine requires that a role be created so that certificates can be issued against it. When certs are issued, services that take ingress traffic can TLS secured.
This PR adds functionality to create these roles."
> Create PKI roles so services can create certificates

- core/src/main/scala/Config.scala
- core/src/main/scala/Workflow.scala
- core/src/main/scala/package.scala
- core/src/main/scala/scheduler/KubernetesShell.scala
- core/src/main/scala/scheduler/NomadHttp.scala
- core/src/main/scala/scheduler/SchedulerOp.scala
- core/src/main/scala/storage/h2.scala
- core/src/main/scala/storage/op.scala
- core/src/main/scala/workflows/Canopus.scala
- core/src/main/scala/workflows/Magnetar.scala
- core/src/main/scala/workflows/Pulsar.scala
- core/src/test/scala/NelsonSuite.scala
- etc/development/http/http.dev.cfg
- http/src/main/scala/Main.scala
- version.sbt
Replace #254 
Implementing a fix for #252 - Presently untested DO NOT MERGE
This has semi-questionable semantics, but is significantly improved over the behavior in #254 as it allows the authors of workflows to more concisely control how their blueprints are rendered (you could even reach out to another system to retrieve your blueprint definition to fully externalize that logic from nelson). There are some nice side benefits to this:
1. if blueprint rendering fails, you get it in your logs.
2. if you're using the default blueprint, that is also in the output of `nelson stack logs`
> Move blueprint rendering into the workflow

- core/src/main/resources/nelson/defaults.cfg
- core/src/main/scala/Config.scala
- docs/src/hugo/content/documentation/configuration.md
This adds the ability to specify `nelson.pools.default-size` and `nelson.pools.scheduling-size` in the nelson.cfg configuration file, adjusting the number of available threads to match the hardware that Nelson operates on, which is important for larger setups. 
```
default-size = 8
scheduling-size = 4
```
> make the thread pool sizing configurable

- core/src/main/scala/storage/h2.scala
I'm debugging some performance issues in our environment whereby we have 15k records in the `deployments` table, and 95k in the `deployment_statuses` table.
When listing nelson stacks from the cli, the backend server is taking ~15-20s to respond. I isolated the issue to the [listDeploymentsForNamespaceByStatus](https://github.com/getnelson/nelson/blob/master/core/src/main/scala/storage/h2.scala#L412) function call, whereby the SQL query is taking about 15s to return server side (even running h2 locally it takes ~19s).
Looking at the explain plan for the query, h2 is doing multiple unnecessary scans of both tables, due to it using a `LEFT JOIN`.
Altering the query as per this PR to an `INNER JOIN` makes the query return in 1s 🎉 . Attached are the query analyze results for the existing left …
> Performance fix for large deployment tables when fetching status

- project/scalapb.sbt
It appears this version of the plugin needed updating as CI was failing to download it.
> Upgrade sbt-protoc dependency
